### ISSUE TITLE
error compiling with mingw32

### ISSUE THREAD

**Issue by biller23** [lsalzman/enet#1]
$ make
C:/Devel/MinGW/msys/1.0/bin/sh.exe ./libtool --tag=CC   --mode=compile gcc -DPAC
KAGE_NAME=\"libenet\" -DPACKAGE_TARNAME=\"libenet\" -DPACKAGE_VERSION=\"1.3.4\"
-DPACKAGE_STRING=\"libenet\ 1.3.4\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\"
-DPACKAGE=\"libenet\" -DVERSION=\"1.3.4\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1
-DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE
_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR
=\".libs/\" -I. -I./include    -g -O2 -MT callbacks.lo -MD -MP -MF .deps/callbac
ks.Tpo -c -o callbacks.lo callbacks.c
Xcallbacks.Tpo -c -o callbacks.lo callbacks.lo
libtool: compile: warning: libobj name `callbacks.Tpo -c -o callbacks.lo callbac
ks.lo' may not contain shell special characters.
rm: invalid option -- c
Try`rm --help' for more information.
libtool: compile:  gcc "-DPACKAGE_NAME=\libenet\" -DPACKAGE_TARNAME=\"libenet\"
 -DPACKAGE_VERSION=\"1.3.4\" -DPACKAGE_STRING=\libenet 1.3.4\"" "-DPACKAGE_BUGR
EPORT=\\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libenet\" -DVERSION=\"1.3.4\" -DSTDC_H
EADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRIN
G_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1
 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -I. -I./include -g -O2 -MT callbacks.l
o -MD -MP -MF .deps/callbacks.Tpo -c -o callbacks.lo callbacks.c"  -DDLL_EXPORT
-DPIC -o .libs/callbacks.Tpo -c -o callbacks.lo callbacks.o
gcc.exe: error: callbacks.o: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated.
make: **\* [callbacks.lo] Error 1

**Comment by Croydon** [comment]
This is a really old issue. Unless there is more up-to-date feedback on failing MinGW builds, this might get closed.

**Comment by biller23** [comment]
Sorry I forgot It was still open. Now it works fine.
