### ISSUE TITLE
Some strange delays on Windows

### ISSUE THREAD

**Issue by Tarik02** [lsalzman/enet#108]
I have an enet server and client. If I run the server on Windows, it works very slowly (high CPU usage, high sending delays (5-10 secs), disconnections). If I run the server on Linux (WSL, Android), everything goes normally. Client works normally no matter on what platform.

**Comment by dbechrd** [comment]
This issue does not contain nearly enough information to diagnose or reproduce.

- Are you using reliable messages or unreliable messages?
- How did you connect to the server (e.g. loopback address or public IP)?
- How much data / what kind of data are you sending?
- What other applications are you running that could affect your network's reliability?

There are infinitely many reasons this behavior could occur. My guess is that your server code has a bug that is causing it to send more data than you think, or you're calling `enet_host_service` with a timeout which causes the server to block.

**Comment by Tarik02** [comment]
I'm sorry, but I don't have an ability and need to reproduce the issue anymore.
