### ISSUE TITLE
How many consecutive connections can enet handle?

### ISSUE THREAD

**Issue by elieobeid7** [lsalzman/enet#110]
I'm using Godot game engine to create a multiplayer game, it supports UDP, TCP and websockets. According to my research UDP is the only one reliable, they use Enet.

I didn't get a decisive answer from godot community on how many consecutive connections Enet can handle, many create a new server instance using docker per room, I don't like that

I want to have 8 players per room, how many consecutive connections can Enet handle before that I have to create a new  docker instance? If there's no good answer, I'd like to know the safest bet before creating an instance.

**Comment by lsalzman** [comment]
It can handle 4K connections on a single host.

**Comment by elieobeid7** [comment]
Thank you so much, a single host meaning a single docker container right? not a single server? 

How to scale enet? is docker the way to go?

**Comment by lsalzman** [comment]
ENet has nothing to do with docker at all. I have no idea what Godot has
done that would suddenly require docker. ENet is only a UDP protocol.

**Comment by elieobeid7** [comment]
I meant to ask, if you need to handle more than 4k, what would you do? they use docker to handle more than 4k connections that's all. In any case, if you need to handle 5k, you create a cluster right? 

I'm closing this issue, you solved it so fast, thank you.

**Comment by lsalzman** [comment]
Trying to do more than 4K connections on a single host would not really be
that efficient, because you are stressing one single OS process trying to
deal with all the load of them. So you might want to reconsider your
networking architecture so that those connections get split over to
multiple hosts/servers and so they you can take advantage of parallelism.

**Comment by elieobeid7** [comment]
Awesome thank you!
