### ISSUE TITLE
Connection timeout when 2 enet host in same process

### ISSUE THREAD

**Issue by Benau** [lsalzman/enet#119]
In the mar 4 commit seems that the connected peer disconnected after ~1 second. This happen when you create 2 enet hosts in same process and connect to one another.

**Comment by lsalzman** [comment]
I would have to see your code to understand the problem.

**Comment by Benau** [comment]
you are great, b4c427059aa39ce42ae4c82afcfe617dea255c4d seems to fix it! ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)

**Comment by Benau** [comment]
Do you know why now roundTripTime for same process 2 enet hosts sometimes will become 1-2ms instead of 7ms? (notice: it will stay 1(or 2)ms thorough the program, next time it restarts it may become 8ms or 1, 2ms and stay that)

Basically now enet roundTripTime cannot return consistent 7ms ping anymore for every start of program, which before does

**Comment by lsalzman** [comment]
This is due to the fact that the accounting is done at a precision of
milliseconds, and is doing some divisions which are getting quantized, so 1
/ 8 is just rounding off to zero, and the averages never change because of
that for values <= 8. I can try a hack to fix this.

**Comment by imtrobin** [comment]
I'm seeing similar hiccup in the round trip timing , as described here

https://github.com/lsalzman/enet/issues/103#issuecomment-606385436

**Comment by JayFoxRox** [comment]
See https://github.com/lsalzman/enet/commit/6991632abf1af161f332bf38bd8517c7c2834b58 - this has been changed 2 days ago. That might already affect it.

**Comment by imtrobin** [comment]
I updated to [f89e598](https://github.com/lsalzman/enet/commit/f89e5986d06033f6b6421163444960f78dec99f8)

There is still a hiccup, lesser though

https://filedn.com/l3TGy7Y83c247u0RDYa9fkp/temp/code/TestEnetServer.zip

Compile in x86, press 4 or 5 to send reliable/unreliable
