### ISSUE TITLE
Question Regarding to Sequence Number Overflow

### ISSUE THREAD

**Issue by sofmz** [lsalzman/enet#121]
I see the code of Enet using 16bit to store the sequence number of packets. What would happen if the number of packets sent/received to a peer is greater than 65536? Does it get reset and Enet handles the situation transparently to developer? I wonder if Enet allows days of frequent communication between a client and a server without disruption.

**Comment by lsalzman** [comment]
It works just fine. There is explicit handling of such overflow to ensure that they are sequenced as if they had a virtual sequence number that sequences after all other sequence numbers that were pre-rollover.

**Comment by sofmz** [comment]
Thanks!

**Comment by sofmz** [comment]
Thanks again for your helpful response. A bit more question on the enet reliable packet. Does enet preemptively send redundant data of a reliable packet to combat latency caused by packet loss at the expense of higher bandwidth usage? Or should I expect it to be closer to tcp with selective acknowledgment?

The reason I'm asking is that I've started to question my initial plan of using enet unreliable packet to send stream of unacknowledged inputs to other peer every tick, in a case if there is packet loss, the other peer should receive the data in next tick. If enet has already implemented the reliable packet sending in a similar or better way to combat latency, then my initial idea is actually work redundant and unnecessary.

**Comment by lsalzman** [comment]
ENet's reliable packets should be fairly good.
