### ISSUE TITLE
wont initialize

### ISSUE THREAD

**Issue by Alexander9673** [lsalzman/enet#123]
enet wont initialize, i am using crc32 like this
`server->checksum = enet_crc32;`

before that line, i'm doing `enet_initialize();`

then after compiling, it warns me that `server` is used uninitialized in this function.
then after running, i get a segmentation fault.

**Comment by lsalzman** [comment]
I would have to see your code to know what's going wrong, but it sounds like you're not creating a host at all and just assigning to a dangling pointer.

**Comment by Alexander9673** [comment]
Im using napi.h to create a simple enet wrapper for nodejs.
```cpp
#include "napi.h"
#include <string>
#include <iostream>
#include <enet/enet.h>

using namespace Napi;

Number Initialize(const CallbackInfo& args)
{
	Env env = args.Env();

	return Number::New(env, enet_initialize());
}

Number createServer(const CallbackInfo& args)
{
	Env env = args.Env();

	ENetHost* server;
	ENetAddress address;

	server->checksum = enet_crc32;
	enet_host_compress_with_range_coder(server);

	address.host = ENET_HOST_ANY;
	address.port = 17091;

	server = enet_host_create(&address, 32, 2, 0, 0);

	return Number::New(env, 0);	
}

Object Init(Env env, Object exports) {
	exports.Set(String::New(env, "Initialize"), Function::New(env, Initialize));
	exports.Set(String::New(env, "createServer"), Function::New(env, createServer));	
  return exports;
}

NODE_API_MODULE(addon, Init)
```

this is what i have now. I use it by doing
```js
addon.Initialize();
addon.createServer();
```

at nodejs.

**Comment by lsalzman** [comment]
You are assigning to (and calling functions on) a dangling pointer (server in this case). The pointer is, like your compiler says, uninitialized until after you initialize it with "server = enet_host_create(...);". All your stuff that uses the "server" variable must happen after that assignment.

**Comment by Alexander9673** [comment]
but on nodejs, im running initialize first?

**Comment by Alexander9673** [comment]
ah wait nvm i get it ty
