### ISSUE TITLE
enet crashing upon sending packets

### ISSUE THREAD

**Issue by Alexander9673** [lsalzman/enet#124]
Hello, so i was wandering when enet crashes.
When i create packets with c++, it works. (by creating packets, i mean copying data/adding new data to a byte array).
Then i create an ENet packet, then send it which works.

But when i do the same functions on nodejs, it crashes. I pass the created packet to the c++ addon, then create an enet packet, then after sending, it crashes. Any reason why?

```
04 00 00 00 01 00 00 00 ff ff ff ff 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0
0 00 00 00 00 00 00 02 00 02 10 00 00 00 4f 6e 43 6f 6e 73 6f 6c 65 4d 65 73 73
61 67 65 01 02 07 00 00 00 54 65 73 74 69 6e 67 00
```

this is the bytes of the packet being sent.
c++ & nodejs outputs the both though

**Comment by bjorn** [comment]
You'd need to share your code or at least try to get a backtrace, otherwise there is no way for anybody to help you figure out what's going wrong. It's not likely to be a problem in ENet, nor is it likely related to the bytes being sent.

Also, this is a C library whereas nodejs is JavaScript. So, are you using some custom binding code or are you using some else's bindings? In the latter case, which one?

**Comment by Alexander9673** [comment]
This is what im doing, im calling a c++ function on nodejs, since i'm making a binding.
I pass a buffer, which then i cast the data to `BYTE*`, which is an `unsigned char`
Then, i just use `enet_packet_create`  on that data,  which suddenly causes the crash.
I know it's a valid data, since i logged the packet created in c++, and it is the same as the packet created in nodejs.

**Comment by Alexander9673** [comment]
This is not a binding for enet, btw. It's just a binding for a server that uses enet.
This is what i mean by the buffer

```cpp
Buffer<char> buf = info[1].As<Buffer<char>>();
BYTE* data = (BYTE*)buf.Data();
int len = buf.Length();

ENetPacket p = enet_packet_create(data, len, ENET_PACKET_FLAG_RELIABLE);

enet_peer_send(peer, 0, p); // this is where it suddenly closes
```

**Comment by bjorn** [comment]
I assume you forgot to write a `*` in `ENetPacket p`?

In any case, if `enet_peer_send` suddenly closes, it indicates the `peer` and/or `p` pointers may be invalid. Did you check the return value of `enet_packet_create` and where is `peer` coming from?

**Comment by Alexander9673** [comment]
But data is already a pointer. So it isn't necessary to add `*` right?

**Comment by Alexander9673** [comment]
Checked my code, it's already a pointer.

**Comment by Alexander9673** [comment]
The code i gave was an example. here's what's really happening.
```cpp
void test(const CallbackInfo& info)
	{
		string id = info[0].As<String>().Utf8Value();
		Buffer<char> buffer = info[1].As<Buffer<char>>();
		int len = info[2].As<Number>().Uint32Value();
		int indexes = info[3].As<Number>().Uint32Value();

		GamePacket p;

		p.data = (BYTE*)buffer.Data();
		p.len = len;
		p.indexes = indexes;

		Packet::testing(Utils::getPeer(id), p);
	}
```
this function is called by nodejs, which would require peerid, buffer, len, indexes.
it then converts the 3 data to a `GamePacket`
it then gets the peer on the map with the key as `id`. Then runs the function `Packet::testing()`
which is this:
```cpp
void Packet::testing(ENetPeer* peer, GamePacket p)
{
	//GamePacket p = PacketEnd(_packet);
	ENetPacket* packet = enet_packet_create(p.data,
		p.len,
		ENET_PACKET_FLAG_RELIABLE);

	enet_peer_send(peer, 0, packet);
	delete p.data;
}
```

**Comment by Alexander9673** [comment]
Problem fixed, i was sending an invalid packet.

**Comment by wheybags** [comment]
As a side note, I'm not sure where the Buffer type is coming from, maybe some interop library, but you probably don't want to have the delete p.data line at the end of Packet::testing. As that pointer is being derived from Buffer::Data(), I would expect the buffer class should be responsible for freeing it.

**Comment by Alexander9673** [comment]
yeah, that `delete p.data` was the problem.
