### ISSUE TITLE
Q: Right usage of host service and check events

### ISSUE THREAD

**Issue by oktonion** [lsalzman/enet#126]
Since documentation is so minimalistic and examples do not cover `enet_host_check_events()` usage like at all I want to make sure I understand correctly how things works.
Consider the following piece:

Some data:

```cpp
std::shared_ptr<ENetHost> host;
struct {
    std::queue<std::vector<unsigned char>/**/> data;
}receiver;
```

Main loop:

```cpp
ENetEvent event;
        if (enet_host_service(host.get(), &event, 0) > 0)
        {
            /* Wait up to 0 milliseconds for an event. */
            do
            {
                switch (event.type)
                {
                case ENET_EVENT_TYPE_CONNECT:
                {
                    enet_peer_ping_interval(event.peer, 100);
                    break;
                }
                case ENET_EVENT_TYPE_RECEIVE:
                {
                    if (event.packet->dataLength < 1)
                    {
                        enet_packet_destroy(event.packet);
                        continue;
                    }

                    receiver.data.push(std::vector<unsigned char>(event.packet->dataLength));
                    std::vector<unsigned char>& data = receiver.data.back();

                    memcpy(data.data(), event.packet->data, data.size());
                    /* Clean up the packet now that we're done using it. */
                    enet_packet_destroy(event.packet);

                    break;
                }

                case ENET_EVENT_TYPE_DISCONNECT:
                {
                    event.peer->data = NULL;

                    break;
                }
                default:
                    break;
                }
            } while (enet_host_check_events(host.get(), &event) > 0);
        }
```

The logic behind this is that I assume calling `enet_host_service()` once will check for events and process all incoming and outgoing data, ping remote hosts/peers and so on. Then `enet_host_check_events()` loop will process all queued events. 

1. Am i right there or maybe missing something?
2. What the difference would be if I use `enet_host_service(host.get(), NULL, 0) > 0` instead and then `enet_host_check_events(host.get(), &event) > 0` for events in a loop?
3. Also I want to know what the difference would be if I write `while (enet_host_service(host.get(), &event, 0) > 0)` instead of `if (enet_host_service(host.get(), &event, 0) > 0)` ?

**Comment by oktonion** [comment]
Maybe some thoughts from community?

**Comment by bjorn** [comment]
Right, if you're using `enet_host_check_events` in a loop anyway, then you can simplify your code to just:
```c
    enet_host_service(host, 0, 0);
    ENetEvent event;
    while (enet_host_check_events(host, &event) > 0) {
        switch (event.type) {
             // ...
        }
    }
```
If you instead do `while (enet_host_service(host, &event, 0)` then you're allowing both receiving additional messages that arrived after the first call to `enet_host_service` as well as sending messages that got queued as part of handling the events. The downside of this is that it may affect the frequency with which other code in this thread will be executed.

Btw, you can use `enet_host_flush` to make queued messages to go out immediately. It can be a good idea to do this after the handling of events, depending on how often this code gets triggered (otherwise they'd get sent on the next call to `enet_host_service`, which could add some lag to your communication).

Finally, there should be no reason to copy the data in the packet. Ownership of the packet is already passed to you after all.

**Comment by oktonion** [comment]
@bjorn Thx for detailed reply. Could it be that if I use just `enet_host_service(host, 0, 0);` there would be some incoming events while I process `enet_host_check_events(host, &event) > 0` ?

**Comment by bjorn** [comment]
@oktonion I have no time to check the code, but I believe not. There could be incoming data on the socket, but `enet_host_check_events` would not turn it into events. That's done by `enet_host_service`.

I would really advice you to just read the code yourself. While there are some complicated bits, you can usually find the answer to such questions pretty easily.

**Comment by oktonion** [comment]
@bjorn That's clear, thx. However I prefer to read documentation rather than code itself - saves a lot of time. =)

P.S.: Also codebase is a bit of mess now with lots of unused params and even functions.
