### ISSUE TITLE
Possible bug in transmission logic of fragmented packets

### ISSUE THREAD

**Issue by Zerolean** [lsalzman/enet#128]
I've noticed a suspicious behavior when unreliable packets that exceed MTU (without using any packet flags) prevent sending of unreliable packets that below MTU. For example:

1. Sending and receiving packets continuously every 15 milliseconds in the loop.
2. Creating and enqueuing for sending an unreliable packet with 64 bytes in size.
3. Creating and enqueuing for sending an unreliable packet with 2048 bytes in size.
4. Invoking service or flushing the host.
5. The packet that exceeded MTU delivered successfully, but the packet below MTU is most likely not (with ~90% of probability).

It happens on localhost and on remote connections. Packets that exceed MTU and flagged as `ENET_PACKET_FLAG_UNRELIABLE_FRAGMENT` makes this a non-issue.

It also happens when packets that exceed MTU are flagged as reliable.

**Comment by lsalzman** [comment]
In this case there can be some reordering of packets that I think might lead to this behavior if you use enet_host_service in a certain way. ENet sends out all reliable packets first, then unreliable ones. This is exacerbated by enet_host_service on the receiving end if you pass in an ENetEvent struct, which may cause it to terminate reading packets early. Calling enet_host_service with a NULL event struct, and then using enet_host_check_events to dequeue all generated events should work around this, I believe.

**Comment by lsalzman** [comment]
Actually, just looked at this in more detail, and the only thing that might actually short-circuit the packet reception loop is connection initiation, not anything else (i.e. packet sending). So what I said shouldn't actually apply to this situation even beyond the fact that reliable packets get sent out first...

**Comment by Zerolean** [comment]
We tried several different approaches to solve this, but only `ENET_PACKET_FLAG_UNRELIABLE_FRAGMENT` helps, and while it resolves this issue, fragmented packets become unreliable of course. We can implement a custom transmission logic on top of unreliable packets for payloads that larger than MTU as a solution, but still trying to determine the root of the problem in the ENet itself.

**Comment by Zerolean** [comment]
Worth noting that if we flag an unreliable packet below MTU as reliable too, then it's delivered just fine as well as a fragmented one.

**Comment by Zerolean** [comment]
Separating unreliable packets and reliable fragmented packets into different channels also make this a non-issue.

**Comment by lsalzman** [comment]
As I noted, the behavior you might be seeing somehow would have to be related to the fact that reliable packets are preferentially sent out first. And then I would guess your actual usage of enet_host_service is somehow suboptimal and exacerbating the issue.  Recoding your usage of enet_host_service might potentially address the issue.

**Comment by Zerolean** [comment]
It happens even in the basic application without any logic, just a program with two hosts exchanging messages in described steps. Using a host with or without a timeout doesn't change anything. Using the service in the approach that you suggested doesn't help, unfortunately. In fact, we always use `enet_host_check_events()` till it indicates that there's nothing to dispatch before polling a host for new events.

**Comment by lsalzman** [comment]
Do you have a testcase that reproduces this behavior that I would be able to try?

**Comment by Zerolean** [comment]
[Here's](https://gist.github.com/Zerolean/11ac0f63c61cc24cb5e68722fc95989f) a basic test.

Using one channel:
![SameChannel](https://user-images.githubusercontent.com/49388731/88254368-972f2500-ccce-11ea-899f-4d67e08aeda1.png)

Using separated channels:
![SeparatedChannels](https://user-images.githubusercontent.com/49388731/88254392-a8783180-ccce-11ea-82c1-64f7d7cfbb15.png)

**Comment by lsalzman** [comment]
I just added a commit to use a unified outgoing command queue that should potentially resolve the issue. It at least fixes the test case.

**Comment by Zerolean** [comment]
Thank you. It works as intended now.
