### ISSUE TITLE
How does ENet make sure its Packet dataLength is not illegaly modified?

### ISSUE THREAD

**Issue by playingoDEERUX** [lsalzman/enet#130]
is the packet datalength passed as bytes in the enet packet header it self (and so seems modifiable)?

**Comment by lsalzman** [comment]
You can enable packet checksums if you are concerned about that

**Comment by NotAFile** [comment]
Checksums can't protect against that (you can just recalculate the checksum). ENet does checks that dataLength is within bounds of the buffer, which is really all that is needed. If you require full authenticity you will need to layer your own cryptography, e.g. libsodium's `crypto_auth_verify`.
