### ISSUE TITLE
unresolved external symbol __ in enet.lib  (Visual Studio 2019)

### ISSUE THREAD

**Issue by kireita** [lsalzman/enet#131]
Hello there,

i followed the basic ENet tutorial [video](https://www.youtube.com/watch?v=FxrKS_1zE9s) and when i tried to compile the server i get these errors:
![image](https://user-images.githubusercontent.com/25864917/89720782-46117780-d9d6-11ea-9f7f-a9a3eb738b9a.png)

i am using Visual Studio 2019 and i have included both the include and libraries:
![image](https://user-images.githubusercontent.com/25864917/89720906-a0f79e80-d9d7-11ea-8da7-3ece6064847e.png)
![image](https://user-images.githubusercontent.com/25864917/89720817-925cb780-d9d6-11ea-9460-51f195285739.png)
![image](https://user-images.githubusercontent.com/25864917/89720823-9dafe300-d9d6-11ea-859b-c9ef8e1598b0.png)
![image](https://user-images.githubusercontent.com/25864917/89720895-6988f200-d9d7-11ea-8436-c31a3fad631b.png)

and i cannot get it to work for the life of me, can someone please help me and tell me what I'm doing wrong?

thanks in advance.

**Comment by lsalzman** [comment]
You need to link to winsock and winmm. I believe it says this in the faq

**Comment by kireita** [comment]
@lsalzman  you mean in this [page](https://github.com/lsalzman/enet/blob/master/docs/FAQ.dox) ?
can you help me with that? a few screenshots would be enough for me.

**Comment by JayFoxRox** [comment]
https://github.com/lsalzman/enet/blob/eda26a26d913a1e86f44fae725049c97dc1ce5a8/docs/install.dox#L36-L40

**Comment by kireita** [comment]
Thank you! this was the problem i was having, too bad the video did not explain that but im happy you could help me man!
