### ISSUE TITLE
How to identify disconnected peer?

### ISSUE THREAD

**Issue by DmitruMoth** [lsalzman/enet#138]
Is there are any way to identify disconnected peer on a server side? As i understand, all values of ENetPeer cleans after get disconnect event

**Comment by bjorn** [comment]
According to [the tutorial](http://enet.bespin.org/Tutorial.html):

> An event of type ENET_EVENT_TYPE_DISCONNECT is returned when a connected peer has either explicitly disconnected or timed out. Only the "peer" field of the event structure is valid for this event and contains the peer that disconnected. Only the "data" field of the peer is still valid on a disconnect event and must be explicitly reset.

So, the way to identify a disconnected peer is to handle the `ENET_EVENT_TYPE_DISCONNECT` event, and the "data" field will not be cleaned so you generally should point this at some instance that allows you to know which client disconnected.

**Comment by DmitruMoth** [comment]
Should i `delete` a pointer or just set to `nullptr`?
