### ISSUE TITLE
enet_peer_ping not enough to keep connection alive

### ISSUE THREAD

**Issue by imtrobin** [lsalzman/enet#140]
Hi, I'm loading a large data on the server while processing a packet, and if it takes really long (50 sec) , the client will disconnect. I'm trying to keep the connection alive by ping a enet_peer_ping every 50ms, which does not work

```
   while (true)                              // server
      EnetEvent event;
      enet_host_service (server, &event, 0);
      switch (event.type)
          case ENET_EVENT_TYPE_RECEIVE: 
                 // here I load a very large data, which takes 50 sec async .e.g I call enet_peer_ping while data is loading
                 while (data not load)
                      // load data asynchronously
                      enet_peer_ping (ConnectedClient);
                     Sleep (50);
```

I see enet_peer_ping is sending outgoing command but that is not enough. Should it be receiving incoming events too for this to work?

I do not want to enet_host_service in there as I do not want to handle messages (it's already handled in outer loop).

**Comment by bjorn** [comment]
> I do not want to enet_host_service in there as I do not want to handle messages (it's already handled in outer loop).

You should probably still service the host to keep the connection alive (and no need for the ping, since regular pings happen automatically anyway). If you do not want to handle events, pass `NULL` for the `event` parameter.
