### ISSUE TITLE
reliable channel locked after ack from receiver discarded while continuing to send burst of reliable data

### ISSUE THREAD

**Issue by westdev005** [lsalzman/enet#141]
I came across a scenario where the reliable channel has locked up, making no further progress with receiver.
This occurs when an ACK from receiver towards sender is discarded while the sender continues send a burst of reliable packets.

In this particular situation, the sender is missing an ack for sequence 0x328b
However, the senders logic allows sending future reliable packets up until sequence 0xc000, based on the logic in send_reliable_outgoing_commands.

With a missed ack for 0x328b, the used reliable window #3 is nonzero.  The sender was able to send thru window 0xb and stops at beginning of window 0xc.
Note, even though the ENET_PEER_FREE_RELIABLE_WINDOWS is 8, there are only 7 free windows (c, d, e, f, 0, 1, 2)

Now, the receiver did actually receive 0x328b, and in now is in window 0xb expected 0xc to arrive.
When the sender resends 0x328b, the receiver does not reply to that ack as there is logic apparently to prevent the sender from getting too far ahead – however this is an old packet.
In this scenario, the sender retries the old packet 0x328b forever.
Note, if the sender was resending a packet in window 4, say 0x428b, the receiver would have acked.

To test a fix for this very specific condition, I added the ‘+1’ immediately following ENET_PEER_FREE_RELIABLE_WINDOWS in both locations below in enet_protocol_send_reliable_outgoing_commands.  This now prevents the lockup for this specific scenario.

enet_protocol_send_reliable_outgoing_commands (ENetHost * host, ENetPeer * peer, ENetChannel* channel)
{
    ENetProtocol * command = & host -> commands [host -> commandCount];
    ENetBuffer * buffer = & host -> buffers [host -> bufferCount];
    ENetOutgoingCommand * outgoingCommand;
    ENetListIterator currentCommand;
    enet_uint16 reliableWindow;
    size_t commandSize;
    int windowExceeded = 0, windowWrap = 0, canPing = 1;

    currentCommand = enet_list_begin (& channel -> outgoingReliableCommands);

    while (currentCommand != enet_list_end (& channel -> outgoingReliableCommands))
    {
       outgoingCommand = (ENetOutgoingCommand *) currentCommand;

       reliableWindow = outgoingCommand -> reliableSequenceNumber / ENET_PEER_RELIABLE_WINDOW_SIZE;

       if (! windowWrap &&
           outgoingCommand -> sendAttempts < 1 &&
           ! (outgoingCommand -> reliableSequenceNumber % ENET_PEER_RELIABLE_WINDOW_SIZE) &&
           (channel -> reliableWindows [(reliableWindow + ENET_PEER_RELIABLE_WINDOWS - 1) % ENET_PEER_RELIABLE_WINDOWS] >= ENET_PEER_RELIABLE_WINDOW_SIZE ||
             channel -> usedReliableWindows & ((((1 << ENET_PEER_FREE_RELIABLE_WINDOWS+1) - 1) << reliableWindow) |
               (((1 << ENET_PEER_FREE_RELIABLE_WINDOWS+1) - 1) >> (ENET_PEER_RELIABLE_WINDOWS - reliableWindow)))))
         windowWrap = 1;

**Comment by lsalzman** [comment]
Okay, I added this fix into the repo.
