### ISSUE TITLE
sender allowed use 8 windows but receiving side queues and acks only 7

### ISSUE THREAD

**Issue by westdev005** [lsalzman/enet#143]
Hello,
According to the sending logic in enet_protocol_check_outgoing_commands (protocol.c), the sender is allowed to send reliable packets using up to 8 of the 16 windows.  
For example, the sender may have an old unacknowledged packet in window 6, say with sequence 0x6112.  In this case, the sender is allowed to send packets with sequence numbers into the 0xd range (e.g. 0xd222) – and thus is using 8 windows 6, 7, 8, 9, a, b, c, d.   

On the receiving side, many of these packets are queued waiting on retransmit of the old packet 0x6112.
The handler of the reliable packet performs a check on the incoming sequence number to ensure it’s within range before queuing and responding with an Ack.

If the packet is outside the range, the packet is not queued and an Ack is not generated, causing the sender to retry later.

Although the sending side is allowed to consume 8 windows, it is noticed that on the receiving side, only 7 windows will result in queuing and acknowledging the packet.

If we take the example above, the receivers channel sequence number would be 0x6111 
If a reliable packet with sequence 0xd222 is processed, the logic to queue and ack will fail.  (logic to queue is similar to deciding to Ack)

So, the question is, should the sender be allowed to send using up to 7 windows instead of 8?  In order to prevent sending in the 8th window which would result in discarded packet and dropped ack?  

reliableWindow = d
currentwindow = 6

        if (reliableWindow >= currentWindow + ENET_PEER_FREE_RELIABLE_WINDOWS - 1 && reliableWindow <= currentWindow + ENET_PEER_FREE_RELIABLE_WINDOWS)
          return NULL;

if (0xd  >= 6 + 8-1  && 0xd <= 6 + 8)
if (0xd >= 0xd && 0xd <= 0xe)
return with no ack

ENetAcknowledgement *
enet_peer_queue_acknowledgement (ENetPeer * peer, const ENetProtocol * command, enet_uint16 sentTime)
{
    ENetAcknowledgement * acknowledgement;

    if (command -> header.channelID < peer -> channelCount)
    {
        ENetChannel * channel = & peer -> channels [command -> header.channelID];
        enet_uint16 reliableWindow = command -> header.reliableSequenceNumber / ENET_PEER_RELIABLE_WINDOW_SIZE,
                    currentWindow = channel -> incomingReliableSequenceNumber / ENET_PEER_RELIABLE_WINDOW_SIZE;

        if (command -> header.reliableSequenceNumber < channel -> incomingReliableSequenceNumber)
           reliableWindow += ENET_PEER_RELIABLE_WINDOWS;

        if (reliableWindow >= currentWindow + ENET_PEER_FREE_RELIABLE_WINDOWS - 1 && reliableWindow <= currentWindow + ENET_PEER_FREE_RELIABLE_WINDOWS)
          return NULL;
    }

**Comment by westdev005** [comment]
To avoid this specific condition, I changed the '+1' to ‘+2’ immediately following ENET_PEER_FREE_RELIABLE_WINDOWS in both locations below in enet_protocol_send_reliable_outgoing_commands.

**Comment by lsalzman** [comment]
I incorporated this fix.
