### ISSUE TITLE
How can peer->data members be accessed thread safely?

### ISSUE THREAD

**Issue by playingoDEERUX** [lsalzman/enet#144]
This question sounds odd but,

Imagine the case where you have a struct called "ClientData" contained a few strings or ints or whatever, simply data and you assign it to the peer like this:

peer->data = new ClientData;

And when the peer disconnects, you delete it like this:
delete peer->data;
peer->data = nullptr;

----------------------------------------------------------------------------------------------------------------------------------------------

Now, what if I want to use multiple servers on the same server process using threads that loop through all allocated peers of every server, and try to access this data/member? Is it going to be safe? Could it be that peer->data gets deleted while code tries to access it or that peer->data was already deleted as the peer in the other server that was tried to be retrieved its data from disconnects or whatever?

How can I make sure that safety is guaranteed? Is overriding member access a good solution to implement syncronization/deleting whenever required? Or an entire custom function into ENetPeer* ?

I need advice, thanks for any help or knowledge that you may provide!

**Comment by bjorn** [comment]
From [the FAQ](http://enet.bespin.org/FAQ.html):

> **Is ENet thread-safe?**
>
> ENet does not use any significant global variables, the vast majority of state is encapsulated in the ENetHost structure. As such, as long as the application guards access to this structure, then ENet should operate fine in a multi-threaded environment.

So, I don't think you should have multiple threads access the same peer at the same time. Since the peers are owned by the host, and you should only have one thread use the host at a time.

Consider which part you really want to multi-thread. Maybe one thread for handling the raw enet events is enough, and it could just copy the relevant data and dispatch the actual handling of those events to a number of other threads? You just need to be careful when you actually use the ENet API. But due to the performance overhead it may not make sense to have multiple threads use locking to avoid concurrent access to the host.

**Comment by playingoDEERUX** [comment]
Why would it not be safe? Unlike just the peer->data member, the peer it self is statically allocated and usable (given that you check the peer state for ENET_PEER_STATE_CONNECTED) once the ENetHost is initialized. And that is what my loop also addresses, same as contained in enet_host_broadcast except it's used for literally anything.

I want to use mutltthreading to host multiple servers on different ports and have them communicating with each other efficiently. And for some stuff I want all (sub)servers to have access to (certain arrays in this case), where I do know that it is important to have syncronization just for that access.

For everything else, I would really wanna know how an ENetPeer it self is not thread safe (btw, host->peers is being used for the loop which is indeed encapsulated in the ENetHost structure).

Thanks for the response anyways.

**Comment by Cleroth** [comment]
It is not thread-safe because there are no synchronization mechanisms.

> Could it be that peer->data gets deleted while code tries to access it or that peer->data was already deleted

Of course. And probably other data races too. Where are other threads getting their peers? How do they know it's still valid?
