### ISSUE TITLE
enet_range_coder_compress always returns 0

### ISSUE THREAD

**Issue by moien007** [lsalzman/enet#152]
[enet_range_coder_compress()](https://github.com/lsalzman/enet/blob/e3ada4ed750b976833e3d54a9c1179445289bbf6/compress.c#L247) always returns zero.

The following code reproduces the problem (assertion fails).
```c
int main(int argc, char const *argv[])
{
    void* range_coder = enet_range_coder_create();

    const char uncompressed[] = "Hello World!"; 
    char compressed[sizeof(uncompressed) + 1];

    ENetBuffer buffer;
    buffer.data = uncompressed;
    buffer.dataLength = sizeof(uncompressed);
    size_t compressedLen = enet_range_coder_compress(range_coder, &buffer, 1, UINT_MAX, compressed, sizeof(compressed));

    assert(compressedLen != 0);

    return 0;
}
```

**Comment by lsalzman** [comment]
It returns zero because there is insufficient space in the output buffer to store the result. Compression algorithms are never guaranteed to always make data smaller, especially when the data to be compressed is smaller and not very repetitive in the first place.

**Comment by RealYukiSan** [comment]
Is there any function like `enet_range_coder_compress` but doing decompress instead of compress?

**Comment by bjorn** [comment]
@RealYukiSan Yes, it's called [`enet_range_coder_decompress`](http://enet.bespin.org/compress_8c.html#a08cd12b64ecb36ffbf6d3281ff2f3e75). :-)
