### ISSUE TITLE
Any way to instantly trigger disconnect event in server without letting the connected client know?

### ISSUE THREAD

**Issue by playingoDEERUX** [lsalzman/enet#155]
Hello,

I am looking for a way to instantly cause a ENET_EVENT_TYPE_DISCONNECT upon an enet_host_service and without a command being sent to the peer that acknowledges it, I want the disconnection to be instantly forced and silent.

Functions I have taken a look at:

enet_peer_disconnect - This one does disconnect, but notifies the peer which I DO NOT WANT AS STATED ABOVE.
enet_peer_disconnect_now - This one does not cause an ENET_EVENT_TYPE_DISCONNECT, forcing it to be timed out later which is also not instant as I want.
enet_peer_reset - Doesn't notify the peer and doesn't disconnect instantly either, forcing it to be timed out later.
enet_peer_disconnect_later - This one disconnects when there are no waiting packets to be sent but notifies the peer.

I'd very much appreciate help.

**Comment by lsalzman** [comment]
enet_peer_disconnect_now() exists for this reason. It does not cause an event because it just calls enet_peer_reset(), i.e. you simply assume the peer is disconnected, the end. It is unconditional.

**Comment by playingoDEERUX** [comment]
Does enet_peer_disconnect_now() at least free up the peer right away/instantly? I currently want to make it so that when a bot by a hacker attacks our server with many clients, I force a disconnect upon it without it knowing and a session is being free'd right away, however I do not see the peerID decreasing until the timeout is triggered.

**Comment by lsalzman** [comment]
If you don't want the other side to know, just call enet_peer_reset. There is no event generated because it isn't a transaction, it just immediately makes the slot ready for use again

**Comment by playingoDEERUX** [comment]
Thanks for telling me that! Exactly what I needed.
