### ISSUE TITLE
ENet chance of corrupted data packet being undetected and causing ENET_EVENT_TYPE_RECEIVE event?

### ISSUE THREAD

**Issue by playingoDEERUX** [lsalzman/enet#163]
Question in title, what's the chance that ENet checksum (and udp checksum) will be corrupted in a way to match the data too or any other collision that could happen?

Is it equal to TCP, or is it (slightly) worse?

Thanks in advance!

(note: this question may be stupid, but I just want to know some numbers as I am making a comparison of ENet and TCP)

**Comment by lsalzman** [comment]
The ENet checksum that ENet provides optionally (if you enable it) is CRC32 which should be about equivalent to TCP.
