### ISSUE TITLE
Question about enet_host_service timeout and ENet configuration

### ISSUE THREAD

**Issue by playingoDEERUX** [lsalzman/enet#168]
Hello, I wanted to ask if there are different types of recommendations on which timeout to choose depending on what I am going to do (e.g does/should the timeout and perhaps other ENet configurations be modified to get better latency or better throughput for a game?)

I want to know every tip in advance to squeeze the most out of ENet, for best latency and throughput, for example:

- When should I rather use a low timeout (< 1000ms) or a "high" timeout (e.g 6000 ms)
- Will playing around with MTU help boost retransmission when packets are small?
- Are there any other modifications that could be done to ENet that would fit fast paced game rather than some "standardish" service

Thanks!

**Comment by Calinou** [comment]
> Are there any other modifications that could be done to ENet that would fit fast paced game rather than some "standardish" service

ENet is already tuned for fast-paced games by default. [That's what it was designed for](https://cubeengine.com)

If it's not reactive enough, consider increasing your server's tick rate and your network update rate (i.e. the rate at which clients send their inputs to the server).

**Comment by lsalzman** [comment]
Timeouts and retransmission are the enemy in and of themselves, so the goal is always to use unreliable packets, rather than reliable ones, since they have neither of those.
