### ISSUE TITLE
How do I use SOCKS protocol in enet?

### ISSUE THREAD

**Issue by GitOlli** [lsalzman/enet#177]
Hello!

I have been playing around with SOCKS protocol lately, and I was wondering how do you use SOCKS protocol in enet? Does it require custom logic for data receiving and sending?

Best regards: Olli.

**Comment by DrOreo002** [comment]
Hey, I've been wondering the same thing have you found the solution yet?

**Comment by GitOlli** [comment]
Hi, I ended up just modifying ENet to support SOCKS5 UDP. It was kinda hard so i recommend using wrappers as mentioned above, but if you want to do it the hard way you need to follow the "RFC 1928" standard.

**Comment by DrOreo002** [comment]
> Hi, I ended up just modifying ENet to support SOCKS5 UDP. It was kinda hard so i recommend using wrappers as mentioned above, but if you want to do it the hard way you need to follow the "RFC 1928" standard.

Ah alright, thank you

**Comment by Calinou** [comment]
> Hi, I ended up just modifying ENet to support SOCKS5 UDP. It was kinda hard so i recommend using wrappers as mentioned above, but if you want to do it the hard way you need to follow the "RFC 1928" standard.

Could you upload your work to a Git repository? This would be helpful for others :slightly_smiling_face:

**Comment by GitOlli** [comment]
> > Hi, I ended up just modifying ENet to support SOCKS5 UDP. It was kinda hard so i recommend using wrappers as mentioned above, but if you want to do it the hard way you need to follow the "RFC 1928" standard.
> 
> Could you upload your work to a Git repository? This would be helpful for others 🙂

I would want to, but many games use ENet for networking so people would probably use it for malicious purposes.

**Comment by Calinou** [comment]
> I would want to, but many games use ENet for networking so people would probably use it for malicious purposes.

I don't see how SOCKS support can be used for malicious purposes, especially if an existing ENet server does not support SOCKS on its own.

**Comment by GitOlli** [comment]
> > I would want to, but many games use ENet for networking so people would probably use it for malicious purposes.
> 
> I don't see how SOCKS support can be used for malicious purposes, especially if an existing ENet server does not support SOCKS on its own.

The ENet server doesn't need to support SOCKS5 protocol for it to work, because the SOCKS5 server just relays the data. You should read the standard found here -> [https://www.rfc-editor.org/rfc/rfc1928](url)

**Comment by DrOreo002** [comment]
> Hi, I ended up just modifying ENet to support SOCKS5 UDP. It was kinda hard so i recommend using wrappers as mentioned above, but if you want to do it the hard way you need to follow the "RFC 1928" standard.

Hi again, wondering why you choose to modify enet instead of using the wrapper?

**Comment by GitOlli** [comment]
> > Hi, I ended up just modifying ENet to support SOCKS5 UDP. It was kinda hard so i recommend using wrappers as mentioned above, but if you want to do it the hard way you need to follow the "RFC 1928" standard.
> 
> Hi again, wondering why you choose to modify enet instead of using the wrapper?

Because if you would choose to use a wrapper you would have to have an external application open that would do the tunneling.

**Comment by playingoDEERUX** [comment]
My insane ENet socks5 implementation is here: https://github.com/playingoDEERUX/ENetSocks5
It's been designed for one specific game though, but the implementation is inside the enet folder (include and source).

**Comment by GitOlli** [comment]
My ENet socks5 implementation is here: [https://github.com/teocoder/enet-socks5](url)

It's based on [https://github.com/zpl-c/enet](url) so it's single header. It supports async, ipv6, username and pass auth and numerous other things that i'm too lazy to list here because I quit this stuff. Just check for yourself and u will see.
