### ISSUE TITLE
How to handle the event where packet has been acknowledged by client?

### ISSUE THREAD

**Issue by playingoDEERUX** [lsalzman/enet#180]
Hello,

I wanted to ask if there is any possible way to execute a function whenever a certain ENetPacket has been acknowledged by a client, instead of blindly using enet_peer_send and assuming that the packet is gonna arrive and then just calling a function right after.

Is there any way to test the ACKNOWLEDGEMENT of an ENetPacket, thus responding accordingly, or am I forced to call functions blindly after a packet has been enqueued on the host.

Thanks.

**Comment by lsalzman** [comment]
Use the packet freeCallback.
