### ISSUE TITLE
ENet SOCKS5

### ISSUE THREAD

**Issue by playingoDEERUX** [lsalzman/enet#190]
Hello, I wanted to ask if ENet socks5 is possible (especially receiving packets from UDP ENet server) if I package the UDP payload to TCP so that the proxy server sends the udp payload to the destination.

SOCKS5 protocol has a byte to allow for UDP associate packets, meaning that I could use these to communicate?

Any help is appreciated...

**Comment by DrOreo002** [comment]
this have been discussed in https://github.com/lsalzman/enet/issues/177 but sadly OP doesn't want to share their code.

**Comment by thamar30** [comment]
Death to the loser fool user called "Oreo002" (not talking about the OP, but the loser who posted above my reply. 
Death to that daft idiot for using the disgusting first two letters in his nasty username (the stupid first two starting letters, before the word "Oreo002"). Oreo002, I hope you die a tragic death. Your are a cheap loser slave, and hope you burn in agony. Death to you Oreo002 and death to every loser who mentions those stupid two letters. I hope you have a tragic life and painful death. Death to "universities". Shame on you Oreo002, you cheap loser slave.

**Comment by thamar30** [comment]
Death to the idiot user called "Oreo002". Death to that daft loser for using the disgusting first two letters in his ugly username (the first two starting letters, before the word "Oreo002"). 
Oreo002, I hope you die a tragic death. Your are a cheap loser slave, and hope you burn in agony. 
Death to you Oreo002 and death to every loser who mentions those stupid two letters. I hope you have a **tragic life and painful death.**

**Comment by playingoDEERUX** [comment]
My insane ENet socks5 implementation is here: https://github.com/playingoDEERUX/ENetSocks5
It's been designed for one specific game though, but the implementation is inside the enet folder (include and source).

**Comment by DrOreo002** [comment]
> My insane ENet socks5 implementation is here: https://github.com/playingoDEERUX/ENetSocks5 It's been designed for one specific game though, but the implementation is inside the enet folder (include and source).

hi deerux, thanks. I'm now your biggest fan

**Comment by 3ba** [comment]
> > My insane ENet socks5 implementation is here: https://github.com/playingoDEERUX/ENetSocks5 It's been designed for one specific game though, but the implementation is inside the enet folder (include and source).
> 
> hi deerux, thanks. I'm now your biggest fan

https://github.com/zKevz/enet-socks5

**Comment by playingoDEERUX** [comment]
@3ba My implemenation is way superior, as they dont use poll() for ENet internally to bypass 1024 socket limit on all unix-like OS's and windows.

**Comment by playingoDEERUX** [comment]
Also, they don't even have an actual framework lmao
