### ISSUE TITLE
ENet range coder compression optimization?

### ISSUE THREAD

**Issue by playingoDEERUX** [lsalzman/enet#191]
Hello, any plans on optimizing the ENet compression? It seems that it's the thing causing most of the CPU load when an ENet server handles a ton of packets at once.

**Comment by Calinou** [comment]
@playingoDEERUX I think providing a profile to see which functions are the most expensive would make it easier to actually optimize the range coder :slightly_smiling_face: 

You can use something like Linux's `perf` to record on the server, and use [HotSpot](https://github.com/KDAB/hotspot) to display the data.
