### ISSUE TITLE
How does ENet handle max slots?

### ISSUE THREAD

**Issue by playingoDEERUX** [lsalzman/enet#192]
Hello,

I wanted to ask how ENet behaves on an incoming connection when all ENetPeer's on a server have been used up.
Does it just drop the connection/not handle it? Or does it put further connections into a queue until a slot is free again (like a backlog)?

Any answer on this question as always would help, I am using this library a lot :)

**Comment by lsalzman** [comment]
Connections are just dropped. The sending end may try to resend the connect packet a few times before giving up, though..
