### ISSUE TITLE
Request: Tag a new version

### ISSUE THREAD

**Issue by xiota** [lsalzman/enet#232]
It's been three years since the 1.3.17 release, and there have been some incompatible changes, like `ENET_SOCKOPT_TTL`.  Projects that require new features need `enet` to be built from git checkout, but as far as I can tell, such builds still identify as 1.3.17.  So build scripts cannot easily check that the new features are available. 

https://github.com/lsalzman/enet/blob/e0e7045b7e056b454b5093cb34df49dc4cee0bee/configure.ac#L1

**Comment by brad0** [comment]
I noticed this being used as a dependency for Dolphin. I'd prefer to use the system copy of our enet port, but the code is a bit old at .17.

**Comment by xiota** [comment]
Looks like there are [other more active forks](https://github.com/lsalzman/enet/network).  Maybe dolphin devs should make their own fork and try to pull the separate development efforts together.

**Comment by jmallach** [comment]
I'm the Debian packager of Dolphin and I'm currently unable to build the newest beta version against the system enet, as Dolphin has picked up unreleased features in libenet.

**Comment by brad0** [comment]
It is also used by a decent number of other projects so it would be good to have the various bug fixes and improvements rolled out.

```
emulators/citra
games/0ad/base
games/dunelegacy
games/enigma
games/godot
games/godot4
games/naev
games/openomf
games/redeclipse
games/sauerbraten
games/speeddreams
games/sumwars
```

**Comment by lsalzman** [comment]
I'll try to make a new release this weekend.

**Comment by jmallach** [comment]
Yay, thanks a lot, @lsalzman!

**Comment by lsalzman** [comment]
Done, 1.3.18.

**Comment by jmallach** [comment]
Again, thanks! I have opened a request in Debian so the enet maintainer updates to 1.3.18 soon.
