### ISSUE TITLE
Issue with Updating `peer->totalWaitingData`

### ISSUE THREAD

**Issue by aiskiller** [lsalzman/enet#262]
In the `enet_peer_queue_incoming_command()` function, there is an increment operation on `peer->totalWaitingData` corresponding to the code `peer->totalWaitingData += packet->dataLength;`.

Should there also be a decrement operation on `peer->totalWaitingData` within the `enet_peer_remove_incoming_commands()` function, similar to `peer->totalWaitingData -= incomingCommand->packet->dataLength;` to ensure accurate tracking of the total waiting data?

**Comment by lsalzman** [comment]
Should be fixed now.
