### ISSUE TITLE
Add the depencies to readme.md

### ISSUE THREAD

**Issue by Fohlen** [lsalzman/enet#45]
Please add the toolchain requirements to the projects readme.md, otherwise it might be difficult to detect compilation errors _(m4 is a bit cryptic on that)_.
The depencies on Ubuntu 14.04 are:
- [build-essential](http://packages.ubuntu.com/en/trusty/build-essential)
- [automake](http://packages.ubuntu.com/en/trusty/automake) and [autoconf](http://packages.ubuntu.com/en/trusty/autoconf)
- [libtool](http://packages.ubuntu.com/en/trusty/libtool) and [shtool](http://packages.ubuntu.com/en/trusty/shtool)

**Comment by dmex** [comment]
@Fohlen 

Those are build toolchain requirements not library dependencies.

"Library dependencies" are things compiled code actually depends upon to function (e.g. Enet has a library dependency on ws2_32.dll (Winsock2) on Windows).

**Comment by Fohlen** [comment]
anyways it would be nice to have those listed..

**Comment by kirtan95** [comment]
Yup agree with @Fohlen, would be nice to have those listed

**Comment by mrozbarry** [comment]
I'm going to disagree that theses are logical dependencies in terms of
building from source.  I can't see any reason why a beginner programmer
that isn't aware or doesn't already have these dependencies already
installed would not be able to figure it out.  To me, it's like stating you
need a computer to compile this application.

**Comment by RobotCaleb** [comment]
@mrozbarry Are you arguing against making it as easy as possible for someone to get up and running?

**Comment by mrozbarry** [comment]
I think people are taking this personally.  You are all confusing a system dependency vs. a library dependency.

**Comment by nemysis** [comment]
Please add Build dependencies for more OS-es not only Ubuntu

**Comment by Fohlen** [comment]
They should be identical on any other platform, although the package-name might differ..

**Comment by gregoire-astruc** [comment]
If you factor in CMake and premake, these are no longer *mandatory* dependencies.
I can very well build it with CMake + ninja, using clang or even premake + icc should I dare. And then goes away the need for almost everything you said :)

Listing *build* dependencies for each and every OS is cumbersome and, well, **very** OS-dependent.

Basically here you need a build toolchain and system libraries. The rest is information used by package maintainer for each platform :)
