### ISSUE TITLE
git tags for releases ?

### ISSUE THREAD

**Issue by extrawurst** [lsalzman/enet#46]
is it possible to use git tags to mark specific versions in the future ? That makes it easier for authors of bindings for other languages to diff two versions.

**Comment by gregoire-astruc** [comment]
I'd appreciate that very much as well :)

**Comment by Croydon** [comment]
:+1:

**Comment by Extrawurst** [comment]
[image: :+1:]

**Comment by ooxi** [comment]
:+1:

**Comment by Croydon** [comment]
Fixed via https://github.com/lsalzman/enet/issues/77#issuecomment-619607912

**Comment by Croydon** [comment]
@extrawurst Please close this issue as it is fixed
