### ISSUE TITLE
How to get IP:PORT of the outgoing connection?

### ISSUE THREAD

**Issue by nxtreaming** [lsalzman/enet#54]
After I received ENET_EVENT_TYPE_CONNECT from server, How can I find my outgoing connection's IP: PORT?

Thanks

**Comment by Nairou** [comment]
`char clientConnection[32];
enet_address_get_host_ip( &event.peer->address, clientConnection, 32 );
printf( "Client connecting from %s:%i\n", clientConnection, event.peer->address.port );`

**Comment by nxtreaming** [comment]
I express my question in details:

In a ENet Client( enet.client.com): I connected to a ENet server( enent.server.com:12345)

I can obtain the ENet server's IP:PORT (obviously enet.server.com:12345) by checking the event : ENET_EVENT_TYPE_CONNECT in ENet client

On ENet Server I can obtain the ENet Client's IP:PORT(enet.client.com:23456) as well.

My question:

How can I find directly my ENet Client's outgoing IP:PORT (eg: enet.client.com:23456, it is connected to enet.server.com:12345) which is used to connect enet.server.com:12345?

**Comment by Nairou** [comment]
So are you saying you want the client to find the actual IP:PORT it used to connect to the server?

**Comment by lsalzman** [comment]
The only way to get this information in a way that considers all the NAT
nastiness in between is to have the server send a message back to the
client that tells the client what ip and port the server thinks it is at.

**Comment by nxtreaming** [comment]
> So are you saying you want the client to find the actual IP:PORT it used to connect to the server?

@Nairou  Yes.

**Comment by nxtreaming** [comment]
> The only way to get this information in a way that considers all the NAT
nastiness in between is to have the server send a message back to the
client that tells the client what ip and port the server thinks it is at.

@lsalzman , I see.
