### ISSUE TITLE
Enet File sync simulation: The performance (file transfer speed) is far worse than 'scp'

### ISSUE THREAD

**Issue by nxtreaming** [lsalzman/enet#55]
I wanna use ENet to speed the file transfer between two hosts which have worse network connection (packet loss ratio over 5%).

I am disappointed by the performance, it is only 110KB/S, however 'scp' can be over 1024KB/S.

I do not think ENet fails to do such task,  It must be my fault.

The following code is very simple:

I use 3 channels to finish the task:

In server side:

1）Ignite file sync by channel 0 （CONNECT event)
2)  Send packet by channel 2 (Would send max 4 packets to speed the transfer and take into account of  RECEIVE event delay issue)
3)  Send finished message by channel 1

In client side:

1） Ignite file sync by channel 0 ( RECEIVE event)
2） Receive packet by channel 2 and send the received packet count by channel 0 ,  Server  will consume the packet and reply file packet with channel 2.
3)   Close file by channel 1 (RECEIVE event) 

I found some RECEIVE interval of server could be very huge( over 10s).
Why? because such huge delay could degrade the file transfer speed.

The following is my example code:

Server.c

`#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <enet/enet.h>
#include "config.h"

#define  FILENAME  "/relay/100MB-tokyo.bin"

static char file_buffer[256*1024];

int main (int argc, char *argv[])
{
    ENetAddress address;
    ENetHost *server;
    ENetPacket *packet;
    ENetEvent event;
    char host_ip[32] = {0};
    char peer_info[32] = {0};
    char msg_notify[64] = {0};
    int lastEvent = -1;
    int enableDebug = 0;

    FILE *fp = fopen(FILENAME, "rb");
    if (!fp) {
        fprintf(stderr, "Fail to open file.\n");
        exit(0);
    }

    /* Initialize the ENet */
    if (enet_initialize() != 0) {
        fprintf(stderr, "An error (%s) occured while initializing ENet.\n", strerror(errno));
        return EXIT_FAILURE;
    }
    atexit(enet_deinitialize);

    /* Create the server */
    address.host = ENET_HOST_ANY;
    address.port = SHUTTLE_SERVER_PORT;
    server = enet_host_create(&address, 64, 6, 0, 0);
    if (server == NULL) {
        fprintf(stderr, "An error (%s) occured while trying to create ENet server host.\n", strerror(errno));
        exit(EXIT_FAILURE);
    }

    enet_uint32 time0 = 0, time1 = 0, time2 = 0;
    uint64_t packet_size = 0;
    uint64_t packet_count = 0;
    int connected = 0;
    int finished = 0;

    printf("(Slice) Server is running.\n");
    while (1) {
        /* Event dispatcher: MUST not be hanged up. */
        int eventStatus = enet_host_service(server, &event, 2);
        if (eventStatus >= 0) {
            switch (event.type) {
            case ENET_EVENT_TYPE_NONE:
                /* Silence huge repeated NONE events. */
                if (lastEvent != ENET_EVENT_TYPE_NONE) {
                    if (enableDebug)
                        printf("(Slice) No event.\n");
                }
                break;
            case ENET_EVENT_TYPE_CONNECT:
                /* Store any relevant server information here. */
                enet_address_get_host_ip(&event.peer->address, host_ip, sizeof(host_ip) - 1);
                snprintf(peer_info, sizeof(peer_info), "[%s:%d]", host_ip, event.peer->address.port);
                if (event.peer->data)
                    free(event.peer->data);
                event.peer->data = malloc(strlen(peer_info) + 1);
                if (event.peer->data)
                    strcpy(event.peer->data, peer_info);
                snprintf(msg_notify, sizeof(msg_notify), "%s has connected to server", peer_info);
                connected = 1;
                finished = 0;
                time0 = enet_time_get();
                /* Ignite packet sync */
                packet = enet_packet_create(msg_notify, strlen(msg_notify) + 1, ENET_PACKET_FLAG_RELIABLE);
                enet_peer_send(event.peer, 0, packet);
                enet_host_flush(server);
                printf("(Slice) Got a connection from peer: %s:%d.\n", host_ip, event.peer->address.port);
                break;
            case ENET_EVENT_TYPE_RECEIVE:
                time1 = enet_time_get() - time0;
                printf("(Slice) Time: %d, Channel: %d.\n", time1 - time2, event.channelID);
                time2 = time1;
                if (connected) {
                    int64_t received_count = atoi((char*)event.packet->data);
                    while (!finished && received_count + 4 > packet_count) {
                        int ret = fread(file_buffer, 1, sizeof(file_buffer), fp);
                        if (!ret) {
                            printf("(Slice) File sync has finished.\n");
                            if (received_count == packet_count) {
                                finished = 1;
                                snprintf(file_buffer, sizeof(file_buffer), "%d", 1);
                                packet = enet_packet_create(file_buffer, strlen(file_buffer) + 1, ENET_PACKET_FLAG_RELIABLE);
                                enet_peer_send(event.peer, 1, packet);
                                enet_host_flush(server);
                            }
                            break;
                        }
                        packet_size += ret;
                        packet = enet_packet_create(file_buffer, ret, ENET_PACKET_FLAG_RELIABLE);
                        packet_count++;
                        enet_peer_send(event.peer, 2, packet);
                        enet_host_flush(server);
                    }
                    printf("(Slice) packet: received:%d, send: %d, speed: %dKB/S.\n",
                           (int)received_count, (int)packet_count, (int)(packet_size*1000/(time1 * 1024)));
                }
                /* Clean up the packet now that we're done using it. */
                enet_packet_destroy(event.packet);
                break;
            case ENET_EVENT_TYPE_DISCONNECT:
                /* A connected peer has either explicitly disconnected or timed out. */
                if (event.peer->data) {
                    printf("(Slice) %s is disconnected.\n", (char*)event.peer->data);
                    free(event.peer->data);
                } else {
                    enet_address_get_host_ip(&event.peer->address, host_ip, sizeof(host_ip) - 1);
                    snprintf(peer_info, sizeof(peer_info), "[%s:%d]", host_ip, event.peer->address.port);
                    printf("(Slice) Unknown (%s) connection is disconnected.\n", peer_info);
                }
                /* Reset the peer's information. */
                event.peer->data = NULL;
                enet_peer_reset(event.peer);
                lastEvent = -1;
                break;
            default:
                assert(0);
                break;
            }

            lastEvent = event.type;
        } else {
            fprintf(stderr, "(Slice) Something went wrong: %d.\n", eventStatus);
            lastEvent = -1;
        }
    }

    enet_host_flush(server);
    fclose(fp);

    enet_host_destroy(server);
    printf("Server is terminated.\n");

    return 0;
}
`

Clinet.c

`#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <pthread.h>
#include <enet/enet.h>
#include "config.h"

typedef struct ChatContext {
    ENetHost *client;
    ENetPeer *peer;
    volatile int connected;
    volatile int terminated;
} ChatContext;

int main (int argc, char *argv[])
{
    ENetAddress address;
    ENetEvent event;
    ChatContext cc, *pcc = &cc;
    char host_ip[32] = {0};
    char peer_info[32] = {0};
    int lastEvent = -1;
    int enableDebug = 0;
    int trycount = 0;
    int ret;

    memset(pcc, 0, sizeof(*pcc));

    /* Initialize the ENet */
    if (enet_initialize() != 0) {
        fprintf(stderr, "An error (%s) occured while initializing ENet.\n", strerror(errno));
        return EXIT_FAILURE;
    }
    atexit(enet_deinitialize);

    /* Create the client host */
    pcc->client = enet_host_create(NULL, 64, 6, 0, 0);
    if (pcc->client == NULL) {
        fprintf(stderr, "An error (%s) occured while trying to create an ENet client host.\n", strerror(errno));
        exit(EXIT_FAILURE);
    }

    /* Connect to the server */
    enet_address_set_host(&address, SHUTTLE_SERVER_HOST);
    address.port = SHUTTLE_SERVER_PORT;
    pcc->peer = enet_host_connect(pcc->client, &address, 6, 0);
    if (pcc->peer == NULL) {
        fprintf(stderr, "No available peers for initializing an ENet connection.\n");
        exit(EXIT_FAILURE);
    }

    do {
        trycount++;
        printf("(Peer) Try to connect to server: the %dth tryouts.\n", trycount);
        if (enet_host_service(pcc->client, &event, 1000) > 0 && event.type == ENET_EVENT_TYPE_CONNECT) {
            /* We can send packet to server only after we have received ENET_EVENT_TYPE_CONNECT */
            pcc->connected = 1;
            enet_address_get_host_ip(&event.peer->address, host_ip, sizeof(host_ip) - 1);
            snprintf(peer_info, sizeof(peer_info), "[%s:%d]", host_ip, event.peer->address.port);
            if (event.peer->data)
                free(event.peer->data);
            event.peer->data = malloc(strlen(peer_info) + 1);
            if (event.peer->data)
                strcpy(event.peer->data, peer_info);
            printf("(Peer) Connected to server (%s:%d).\n", host_ip, event.peer->address.port);
        }
    } while (trycount < 4 && !pcc->connected);

    if (!pcc->connected) {
        fprintf(stderr, "Fail to connect to server.\n");
        enet_peer_reset(pcc->peer);
        enet_host_destroy(pcc->client);
        exit(EXIT_FAILURE);
    }

    FILE *fp = fopen("/mnt/sdc/tmp/file_sync.bin", "wb");
    if (!fp) {
        fprintf(stderr, "Fail to write file.\n");
        exit(0);
    }

    enet_uint32 time0 = 0, time1 = 0, time2 = 0;
    int64_t packet_size = 0;
    int64_t packet_count = 0;
    char packet_info[32] = {0};

    while (1) {
        /* Event dispatcher: MUST not be hanged up */
        int eventStatus = enet_host_service(pcc->client, &event, 2);
        if (eventStatus >= 0) {
            switch (event.type) {
            case ENET_EVENT_TYPE_NONE:
                /* Silence huge repeated NONE events */
                if (lastEvent != ENET_EVENT_TYPE_NONE) {
                    if (enableDebug)
                        printf("(Peer) No event.\n");
                }
                break;
            case ENET_EVENT_TYPE_CONNECT:
                /* Store any relevant client information here. */
                pcc->connected = 1;
                enet_address_get_host_ip(&event.peer->address, host_ip, sizeof(host_ip) - 1);
                snprintf(peer_info, sizeof(peer_info), "[%s:%d]", host_ip, event.peer->address.port);
                if (event.peer->data)
                    free(event.peer->data);
                event.peer->data = malloc(strlen(peer_info));
                if (event.peer->data)
                    strcpy(event.peer->data, peer_info);
                printf("(Peer) Connected to server (%s:%d).\n", host_ip, event.peer->address.port);
                break;
            case ENET_EVENT_TYPE_RECEIVE:
                if (time0 != 0) {
                    time1 = enet_time_get() - time0;
                    printf("(Peer) Time: %d, Channel: %d.\n", time1 - time2, event.channelID);
                    time2 = time1;
                }
                if (event.channelID == 0) {
                    /* Ignite packet sync */
                    packet_count = 0;
                    snprintf(packet_info, sizeof(packet_info), "%d", (int)packet_count);
                    ENetPacket *packet = enet_packet_create(packet_info, strlen(packet_info) + 1, ENET_PACKET_FLAG_RELIABLE);
                    enet_peer_send(event.peer, 0, packet);
                    enet_host_flush(pcc->client);
                    time0 = enet_time_get();
                }
                else if (event.channelID == 2) {
                    packet_count++;
                    time1 = enet_time_get() - time0;
                    packet_size += event.packet->dataLength;
                    if (fp) {
                        printf("(Peer) channelID:%d, len:%ld.\n", event.channelID, event.packet->dataLength);
                        fwrite(event.packet->data, 1, event.packet->dataLength, fp);
                    }
                    printf("(Peer) Receive speed: %d KB/S.\n", (int)(packet_size*1000/(time1*1024)));
                    snprintf(packet_info, sizeof(packet_info), "%d", (int)packet_count);
                    ENetPacket *packet = enet_packet_create(packet_info, strlen(packet_info) + 1, ENET_PACKET_FLAG_RELIABLE);
                    enet_peer_send(event.peer, 0, packet);
                    enet_host_flush(pcc->client);
                } else if (event.channelID == 1) {
                    if (fp) {
                        fclose(fp);
                        fp = 0;
                    }
                }
                else 
                    printf("(Peer) Got a chat message: %s.\n", (char*)event.packet->data);
                /* Clean up the packet now that we're done using it. */
                enet_packet_destroy(event.packet);
                break;
            case ENET_EVENT_TYPE_DISCONNECT:
                /* A connected peer has either explicitly disconnected or timed out. */
                printf("(Peer) Connection status: %d.\n", pcc->connected);
                if (event.peer->data) {
                    printf("(Peer) %s is disconnected.\n", (char*)event.peer->data);
                    free(event.peer->data);
                } else {
                    /* We fail to receive CONNECT event becasue the server is down. */
                    enet_address_get_host_ip(&event.peer->address, host_ip, sizeof(host_ip) - 1);
                    snprintf(peer_info, sizeof(peer_info), "[%s:%d]", host_ip, event.peer->address.port);
                    printf("(Peer) Unknown (%s) connection is disconnected.\n", peer_info);
                }
                /* Reset the peer's information. */
                event.peer->data = NULL;
                pcc->connected = 0;
                lastEvent = -1;
                enet_peer_reset(event.peer);
                /* Reconnect the server */
                pcc->peer = enet_host_connect(pcc->client, &address, 6, 0);
                if (pcc->peer == NULL) {
                    fprintf(stderr, "No available peers for initializing an ENet connection.\n");
                    enet_host_destroy(pcc->client);
                    ret = EXIT_FAILURE;
                    goto cleanup_pos;
                }
                break;
            default:
                assert(0);
                break;
            }

            lastEvent = event.type;
        } else {
            fprintf(stderr, "(Peer) Something went wrong: %d.\n", eventStatus);
            lastEvent = -1;
            pcc->connected = 0;
            enet_peer_reset(pcc->peer);
            ret = eventStatus;
            goto cleanup_pos;
        }
    }

    ret = 0;

cleanup_pos:
    if (fp)
        fclose(fp);
    pcc->terminated = 1;
    enet_host_destroy(pcc->client);
    printf("Client is terminated.\n");

    return ret;
}
`

**Comment by lsalzman** [comment]
enet_host_flush is not a replacement for calling enet_host_service. Nor do
you want to be calling enet_host_flush on every packet send.
 So, basically, you're not using it like it's supposed to be used.

**Comment by nxtreaming** [comment]
> enet_host_flush is not a replacement for calling enet_host_service. Nor do
you want to be calling enet_host_flush on every packet send.
 So, basically, you're not using it like it's supposed to be used.

I removed enet_host_flush(), but the performance is still much worse than 'scp'

**Comment by nxtreaming** [comment]
@lsalzman 

In the following constant, which one has the most effect on network throughput in the case of file transfer ?

enum
{
   ENET_HOST_RECEIVE_BUFFER_SIZE          = 256 * 1024,
   ENET_HOST_SEND_BUFFER_SIZE             = 256 * 1024,
   ENET_HOST_BANDWIDTH_THROTTLE_INTERVAL  = 1000,
   ENET_HOST_DEFAULT_MTU                  = 1400,
   ENET_HOST_DEFAULT_MAXIMUM_PACKET_SIZE  = 32 * 1024 * 1024,
   ENET_HOST_DEFAULT_MAXIMUM_WAITING_DATA = 32 * 1024 * 1024,

   ENET_PEER_DEFAULT_ROUND_TRIP_TIME      = 500,
   ENET_PEER_DEFAULT_PACKET_THROTTLE      = 32,
   ENET_PEER_PACKET_THROTTLE_SCALE        = 32,
   ENET_PEER_PACKET_THROTTLE_COUNTER      = 7,
   ENET_PEER_PACKET_THROTTLE_ACCELERATION = 2,
   ENET_PEER_PACKET_THROTTLE_DECELERATION = 2,
   ENET_PEER_PACKET_THROTTLE_INTERVAL     = 5000,
   ENET_PEER_PACKET_LOSS_SCALE            = (1 << 16),
   ENET_PEER_PACKET_LOSS_INTERVAL         = 10000,
   ENET_PEER_WINDOW_SIZE_SCALE            = 64 * 1024,
   ENET_PEER_TIMEOUT_LIMIT                = 32,
   ENET_PEER_TIMEOUT_MINIMUM              = 5000,
   ENET_PEER_TIMEOUT_MAXIMUM              = 30000,
   ENET_PEER_PING_INTERVAL                = 500,
   ENET_PEER_UNSEQUENCED_WINDOWS          = 64,
   ENET_PEER_UNSEQUENCED_WINDOW_SIZE      = 1024,
   ENET_PEER_FREE_UNSEQUENCED_WINDOWS     = 32,
   ENET_PEER_RELIABLE_WINDOWS             = 16,
   ENET_PEER_RELIABLE_WINDOW_SIZE         = 0x1000,
   ENET_PEER_FREE_RELIABLE_WINDOWS        = 8
};

I think I MUST adjust one of variables  to achieve the better network throughput.

Thanks.

**Comment by lsalzman** [comment]
ENet is not a replacement for TCP for bulk transfers, sorry. It is meant
for unreliable packet transfer, primarily.

**Comment by nxtreaming** [comment]
Thanks

**Comment by Nairou** [comment]
> ENet is not a replacement for TCP for bulk transfers, sorry. It is meant for unreliable packet transfer, primarily.

I'm curious, can you explain why? Does ENet have more overhead than TCP does? I know UDP is capable of bulk transfer if you model it after TCP, but I don't know what the difference is between that and ENet.

**Comment by nxtreaming** [comment]
> I'm curious, can you explain why? Does ENet have more overhead than TCP does? I know UDP is capable of bulk transfer if you model it after TCP, but I don't know what the difference is between that and ENet.

I think the ENet's ARQ (Automatic Repeat reQuest) algorithm does not suit for bulk transfer.

**Comment by nxtreaming** [comment]
I  wanna to implement multi-path transfer based on ENet, I am aiming to transfer data between 2 systems as fast as possible over multiple UDP paths. it would be a UDP version of WDT (https://github.com/facebook/wdt).

**Comment by lsalzman** [comment]
The idea was always that most of your data is sent unreliable. ENet is a
game networking library. If you try to use it like TCP, TCP will always
win. In situations where you need to send a lot of unreliable updates, ENet
wins, because TCP simply can't do this at all, and will lose because of the
latency the extra reliability it incurs, no matter how much TCP has
optimized it.

Use ENet for what it is good for. If you want TCP, there's no reason you
simply shouldn't just be using TCP. If you're only sending bulk reliable
data, then, again, use TCP.

**Comment by nxtreaming** [comment]
> Use ENet for what it is good for. If you want TCP, there's no reason you
simply shouldn't just be using TCP. If you're only sending bulk reliable
data, then, again, use TCP.

I wanna use UDP to optimize the reliable data transfer in the scenario of high packet loss network environment. TCP  fails to establish a stable connection if the packet lost ratio is over 30%.
