### ISSUE TITLE
ENetPeer.packetsSent resets after 21

### ISSUE THREAD

**Issue by winduptoy** [lsalzman/enet#56]
I've only connected to a host and then started reading my `ENetPeer.packetsSent` property. It counts from 0 to 21, and then resets to zero.

Is this expected behavior? `packetsSent` is a 32 bit unsigned integer, so shouldn't this count up to the billions before rolling over?

**Comment by lsalzman** [comment]
It's an undocumented variable only used internally for tracking packet
loss. Use it with care if you haven't read the code the code to figure out
its behavior. It resets every packet loss measurement epoch, so basically
any call to enet_host_service could potentially reset it to 0.
