### ISSUE TITLE
How to get  size of the outgoing reliable packet queue for a specified peer and channel?

### ISSUE THREAD

**Issue by nxtreaming** [lsalzman/enet#57]
I fail to find a public API to obtain the size of the reliable outgoing packet queue.

Thanks

**Comment by zhengchengbin610** [comment]
@nxtreaming  Hi Friend , Do you find a way  to obtain  the  outgoing packet size ? Thanks

**Comment by nxtreaming** [comment]
@zhengchengbin610 Sorry, I have no answer, I just test enet, I finally do not use it in my project.
