### ISSUE TITLE
is it a bug? enet  discarded some command that were not dispatched in queue when it received disconnect command

### ISSUE THREAD

**Issue by liuchengguang** [lsalzman/enet#59]
it's must be a bug:
  when enet call 'enet_protocol_receive_incoming_commands'  in routine ' enet_host_serive', if it received disconnect command(ENET_PROTOCOL_COMMAND_DISCONNECT), in the handler  'enet_protocol_handle_disconnect' , enet  would reset all of queues of the ENetPeer, and also changed the peer's status from ENET_PEER_STATE_CONNECTED to  ENET_PEER_STATE_ZOMBIE!  and  some commands that was in peer's  dispatchedCommands, queues, would be discarded forever! 

and then in 'enet_protocol_dispatch_incoming_commands' ,  enet would just fire the disconnect event according to peer's status(ENET_PEER_STATE_ZOMBIE), 

anybody found this ?

**Comment by lsalzman** [comment]
That's not a bug. That's how it's supposed to work. Use
enet_peer_disconnect_later if you want to make sure in-flight data is
completely acknowledged before disconnect.

**Comment by liuchengguang** [comment]
thx！got  it!
