### ISSUE TITLE
Provide consistent peer/host ID

### ISSUE THREAD

**Issue by reduz** [lsalzman/enet#63]
I am not finding any way to obtain a unique ID for each peer and host.
I know I can do it myself, but it's considerable work and complexity, as I have to delay all peer connected  notifications until I receive the unique ID for each one, and more points of failure for every one that has to do it. 
This makes a lot more sense as part of ENet internal protocol than something users have to make themselves.

**Comment by reduz** [comment]
Nevermind, realized ENet server always connects with data==0, so can simply use non-zero unique IDs

**Comment by pqftgs** [comment]
There's also event.peer->incomingPeerID
