### ISSUE TITLE
How to get file descriptor to poll.

### ISSUE THREAD

**Issue by JontomXire** [lsalzman/enet#64]
Hi,

sorry I am asking here, but I couldn't find anywhere else to ask.

How do I get the file descriptor(s) used by enet so I can poll them simultaneously with any other file descriptors/event loops in my program?

I don't mean to be rude, but running the enet_host_service() with a zero timeout every so often is a bit lame and really doesn't work fantastically well with an event driven model. I generally prefer to write single threaded applications except where there is an actual benefit other than general architectural laziness (e.g. blocking hardware access such as file IO to hard drive), and to do that effectively requires a single event loop which polls all possible event sources simultaneously. Hence I need to obtain the file descriptor(s).

I was planning on writing a GUI app using this library (which I have to say looks amazing - I was very sceptical at first, but it actually looks so cool) and passing networking file descriptors to the X/motif event loop for monitoring along with X events. Thus my code can spring to life whenever an event occurs rather than having to poll X events with a timeout and then call enet_host_service() which is not very responsive to network activity. Also polling a socket with an infinite timeout is much more efficient than repeatedly polling with a zero timeout.

Thanks.

JX.

**Comment by lsalzman** [comment]
host-.socket

**Comment by JontomXire** [comment]
Thanks.
