### ISSUE TITLE
IP address change on peer causes messages to fail in 1 direction behind some routers

### ISSUE THREAD

**Issue by deltars** [lsalzman/enet#74]
With our application using enet with win32, we were able to connect over LAN address, but we were unable to connect to the host when using internet IP address.

The ports are forwarded correctly, and putting break points / logging shows the packets are arriving.

However, the first packet that arrives is addressed with the router IP address, rather than the client peers address. Subsequent packets arrive with the correct IP address, just the first packet is addressed from the router.

This means that on the host, enet rejects all packets except for the first one.

Interestingly, on the host, all packets get sent to the routers IP, and they reach the destination without problem.

Removing the check on the host in protocol.c that checks the packets IP matches the peers IP resolves the issue, but obviously that check is useful for security.

The router is an ASUS RT-AC68U.

I don't think the router is behaving correctly by re-addressing the first packet to be from the router, but regardless, I think Enet should work even with strange behaviors on routers. It is also possible that a peer changes IP address during the connection for other reasons and I think Enet should be able to handle this.

**Comment by nbrignon** [comment]
you have to implement a NAT traversal solution (maybe combining UPnP/Sturn)

**Comment by deltars** [comment]
I will follow up as the thread has been rezzed. As pointed out, UPnP, Stun and also hole punching are techniques used to deal with connection issues.

This doesn't really apply to the case I am describing where a route exists / ports forwarded, but you experience addresses changing on a connection between one packet and the next. My specific case is probably related to my wonky router, but many routers are, and this is actually a general symptom with many causes. I think I remember reading Carmack discussing on a mailing list that they found addresses could change back and forth when developing Quake.

For us, we ended up writing our own library, inspired by enet. We start our packets off with a unique key that identifies the peer and the address is ignored (secure enough for video games).

Much credit to enet and its authors for creating a fantastic library. However, the library isn't actively maintained and this problem is a serious one, as some users will experience networking issues. For this reason, I wouldn't consider enet suitable for production.

**Comment by deltars** [comment]
I will follow up as the thread has been rezzed. As pointed out, UPnP, Stun and also hole punching are techniques used to deal with connection issues.

This doesn't really apply to the case I am describing where a route exists / ports forwarded, but you experience addresses changing on a connection between one packet and the next. My specific case is probably related to my wonky router, but many routers are, and this is actually a general symptom with many causes. I think I remember reading Carmack discussing on a mailing list that they found addresses could change back and forth when developing Quake.

For us, we ended up writing our own library, inspired by enet. We start our packets off with a unique key that identifies the peer and the address is ignored (secure enough for video games).

Its been 6 years and I have no idea if this is still an issue so I will close. But at the time of posting, it was a big problem because some players will have issues so we couldn't use enet for production.
