### ISSUE TITLE
Github release tag

### ISSUE THREAD

**Issue by wheybags** [lsalzman/enet#77]
It would be nice if there were github release tags, at least for the most recent version. As is, I'm not sure which commit corresponds to v1.3.13

**Comment by Croydon** [comment]
Use the search before reporting issues: #46

**Comment by wheybags** [comment]
Ok, that issue is 2 years old with no response, though.
So, can we get some git tags? :s
It's the work of 5 mins, I'd do it myself if I had permissions + knew which commits it was (Is that the issue? If it is, could write a script to diff commits with release tarballs until it finds the correct commits)

**Comment by markatk** [comment]
This would also help including the library as a submodule in other projects, because you can set a specific version to ensure the correct library version you want to use.

**Comment by Croydon** [comment]
Same for package managers.

**Comment by Croydon** [comment]
@lsalzman Since you are preparing a new release, now would be a wonderful time to consider using git tags for new releases 😄

**Comment by lsalzman** [comment]
I can try. Not quite released yet, though. Merely getting ready.

**Comment by lsalzman** [comment]
It's tagged now
