### ISSUE TITLE
Precompiled lib file make link error

### ISSUE THREAD

**Issue by rrrfffrrr** [lsalzman/enet#80]
I'm making an extension(dll) for game maker.
But if i use precompiled lib file in [enet 1.3.13](http://enet.bespin.org/download/enet-1.3.13.tar.gz) make next error.

`main.obj : error LNK2019: unresolved external symbol enet_initialize referenced in function gmenet_initialize`

So i decide to compile lib file and work with it.
precompiled lib has 50kb and mine has 623kb.

I'm using VS 2017 and v141 toolset.

**Comment by Reeley** [comment]
Had the same problem. You have to add the additional dependencies for the linker to work. Go to Properties > Linker > Input

x86: winmm.lib;ws2_32.lib;enet.lib;
x64: winmm.lib;ws2_32.lib;enet64.lib;

**Comment by rrrfffrrr** [comment]
This issue had been inactive and no longer works with enet with game maker, close this issue.
