### ISSUE TITLE
Polling host->socket will not get disconnection event

### ISSUE THREAD

**Issue by wenq1** [lsalzman/enet#85]
When manually adding host->socket to the runloop and check for POLLIN event for read, it seems that one will not get notified of any peer disconnection event. The disconnection event will be detected, however, using a constant polling model by calling enet_host_poll (), which defeats the event-driven runloop model. I understand that peer is merely a userland concept which does not involve socket IO. Is there a way to have both the event-driven model as well as getting the peer disconnection event?

**Comment by lsalzman** [comment]
You can't do that. enet_host_service() does a bunch of timeout management and sending of ACKs that will never happen if you are merely waiting for data on the raw socket. You must call enet_host_service().

**Comment by wenq1** [comment]
Thanks I see.
