### ISSUE TITLE
Before enet_host_service returns a disconnect event, the peer gets reset

### ISSUE THREAD

**Issue by sro5h** [lsalzman/enet#89]
I needed a way to identify an ENetPeer and the `incomingPeerID`, `outgoingPeerID` and `connectID` seemed to fit. Until i discovered that before i receive the `ENET_EVENT_TYPE_DISCONNECT` event the peer is [reset][1].  

Is there some field to identify a connection that is still valid after the disconnect event?

[1]:https://github.com/lsalzman/enet/blob/39a72ab1990014eb399cee9d538fd529df99c6a0/protocol.c#L87

**Comment by lsalzman** [comment]
The "data" field stays whatever you set it to.
