### ISSUE TITLE
Server discover

### ISSUE THREAD

**Issue by Tarik02** [lsalzman/enet#94]
Is there way to discover servers in local network? Or I need to use plain udp sockets?

**Comment by lsalzman** [comment]
You can use ENET_HOST_BROADCAST as the address ip to initiate a connection to a single server on the local network.

If you want to do more complicated things you will have to drop down to sending UDP packets to the broadcast address. But the socket the ENetHost uses is exposed, so it is available for evil things like that.

**Comment by Tarik02** [comment]
Okay, thanks :+1:
