### ISSUE TITLE
corrupted data with ENET_PACKET_FLAG_RELIABLE

### ISSUE THREAD

**Issue by wheybags** [lsalzman/enet#99]
Hi,
I am testing my application with a windows tool that corrupts network packets, [clumsy](https://jagt.github.io/clumsy/).
I noticed that when I use the "Tamper" option (corrupts 10% of packets with random data), the packets still get delivered to my application, with the corrupted data, even when using ENET_PACKET_FLAG_RELIABLE.
It was my understanding that ENET_PACKET_FLAG_RELIABLE would guarantee that all packets delivered to the application were properly reassembled, passed a checksum, and in-order.
Under this assumption, the corrupted packets would be detected by enet, and re-sent until they were delivered successfully, but instead I seem to be receiving corrupted data in my application.
Is this expected behaviour or am I doing something wrong?

**Comment by nxrighthere** [comment]
Checksum functionality is not enabled by default. ENet provides `ENetChecksumCallback` callback  and `enet_crc32()` function for buffers verification. Selective retransmission of corrupted data is not implemented.

**Comment by wheybags** [comment]
Great, that completely solved it!
Thanks
